import os

BOT_TOKEN = os.getenv('BOT_TOKEN')
CRM_ISS = os.getenv("CRM_ISS")
CRM_SECRET_KEY = os.getenv("CRM_SECRET_KEY")
URL_USERS = os.getenv('URL_USERS')
URL_SPECIALTIES = os.getenv('URL_SPECIALTIES')
URL_SCHEDULES = os.getenv('URL_SCHEDULES')
URL_APPOINTMENTS = os.getenv('URL_APPOINTMENTS')
URL_CLIENTS = os.getenv('URL_CLIENTS')
OWNER_CHAT_ID = os.getenv('OWNER_CHAT_ID')
MYSQL_USER = os.getenv('MYSQL_USER')
MYSQL_PASSWORD = os.getenv('MYSQL_PASSWORD')
MYSQL_DATABASE = os.getenv('MYSQL_DATABASE')
MYSQL_PORT = os.getenv("MYSQL_PORT")
MYSQL_HOST = os.getenv("MYSQL_HOST")
REDIS_HOST = os.getenv("REDIS_HOST")
doctor1 = os.getenv('DOCTOR1')
doctor2 = os.getenv('DOCTOR2')
